subdir-ccflags-y += -I$(srctree)/drivers/staging/android/ion/
subdir-ccflags-y += -I$(srctree)/drivers/video/adf/sprd/core/include
subdir-ccflags-y += -I$(srctree)/drivers/video/adf/sprd/bridge/
subdir-ccflags-y += -I$(srctree)/drivers/video/adf/sprd/drv/
subdir-ccflags-y += -I$(srctree)/drivers/video/adf/sprd/drv/shark/

obj-y += drv/
obj-y += core/
