# SPRD Audio Memory Manager Support
SPRD_SOUND_TREE                         := sound/soc/sprd_sharkle/
subdir-ccflags-y                        += -I$(srctree)/$(SPRD_SOUND_TREE)/include/

obj-$(CONFIG_SPRD_AUDIO_MEMORY_MANAGER)  += audio_mem.o
