#SPRD CODEC

SPRD_SOUND_TREE := sound/soc/sprd_sharkle/
ccflags-y += -I$(srctree)/$(SPRD_SOUND_TREE)/codec/sprd

snd-soc-sprd-codec-sc2731-objs   := sprd-codec.o sprd-audio-power.o sprd-headset-sc2731.o
obj-$(CONFIG_SND_SOC_SPRD_CODEC_SC2731)        += snd-soc-sprd-codec-sc2731.o
